
import Abas from "./components/navegacaoAbas/page"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="barraNav">
        <h2>EXERCÍCIO 3-CATÁLOGO DE ESPAÇONAVES</h2>
        <nav>
          <Abas/>
        </nav>
      </div>
        {children}
      </body>
    </html>
  );
}
